export function buildAssistantState({
  tab,
  busy,
  imageForm,
  imageEnhanceEnabled,
  activeKreaModuleLabels,
  videoForm,
  videoDurationSeconds,
  videoEnhanceEnabled,
  videoImage,
  videoEndImage,
  videoAudioJob,
  videoAudioClips,
  videoKeyframes,
  speechForm,
  recognitionForm,
  recognitionFile,
  recognitionSourceVideoJob,
  pagedImageJobs,
  imagePage,
  imagePageSize,
}) {
  return {
    tab,
    busy,
    image: { ...imageForm, enhance_enabled: imageEnhanceEnabled, modules: activeKreaModuleLabels },
    video: {
      ...videoForm,
      duration: videoDurationSeconds,
      enhance_enabled: videoEnhanceEnabled,
      has_start_image: Boolean(videoImage),
      has_end_image: Boolean(videoEndImage),
      has_audio: Boolean(videoAudioJob),
      audio_prompt: videoAudioClips.map((clip) => clip.job.prompt || '').join('\n'),
      audio_instructions: videoAudioClips.map((clip) => clip.job.params?.instructions || '').filter(Boolean).join('\n'),
      audio_clips: videoAudioClips.map((clip) => ({ source_job_id: clip.job.id, start: clip.start, duration: clip.duration })),
      keyframes: videoKeyframes.map((item) => ({ time: item.time, strength: item.strength, has_image: Boolean(item.image) })),
    },
    speech: { ...speechForm },
    recognition: {
      source: recognitionForm.source,
      has_source: Boolean(recognitionFile || recognitionSourceVideoJob || recognitionForm.url.trim()),
      language: recognitionForm.language,
      context: recognitionForm.context,
      translation_mode: recognitionForm.translation_mode,
      target_language: recognitionForm.target_language,
    },
    recent_images: pagedImageJobs.map((job, index) => ({
      index: (imagePage - 1) * imagePageSize + index + 1,
      job_id: job.id,
      status: job.status,
      prompt: String(job.prompt || '').slice(0, 180),
    })),
  }
}
