const {chromium}=require('../../web/node_modules/playwright');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage();await page.goto('http://localhost:8585');
 for(const attrs of ['role="button" aria-haspopup="true" aria-expanded="false" data-shp-area="rvw.pntop"','role="button"']){
 await page.setContent(`<header><h1>한달사용 리뷰쓰기</h1></header><div class="writeForm_write_form__fixture"><div class="productBox_product_box__fixture"><a ${attrs} href="#" id="guide">리뷰 작성 시 포인트 <span>10원</span> 적립</a><div class="productBox_product_area__fixture"><h2 class="productBox_name_product__fixture">반투명 아크릴판 맞춤 재단 매트 엠보아크릴 프라이버시 칸막이 DIY 3T</h2><p>가로사이즈(mm): 300 / 세로사이즈(mm): 300 / 두께: 반투명 3T</p></div></div><div class="writeForm_section__fixture"><h3>상품 리뷰 작성</h3><div><strong>상품에 만족하셨나요?</strong><div role="radiogroup">${[5,4,3,2,1].map(n=>`<button role="radio" data-shp-area="rvw.rate" data-value="${n}" aria-checked="false">${n}</button>`).join('')}</div></div><div><strong>어떤 점이 좋았나요?</strong><div><label for="reviewInput">한 달 동안 사용하시면서 달라진 만족도에 대한 후기를 남겨 주세요. (최소 10자 이상)</label><textarea id="reviewInput" maxlength="5000"></textarea></div></div></div><div class="writeForm_section__fixture"><button>취소</button><button id="register" disabled>등록</button></div></div><div role="status" id="notice"></div>`);
 await page.evaluate(()=>{delete window.__TALK_REVIEW_BRIDGE_V13__;window.chrome={runtime:{id:'test',onMessage:{addListener:f=>window.listener=f}}};window.post=m=>new Promise(r=>listener({type:'TALK_REVIEW_V13',...m},{id:'test'},r));window.guideClicks=0;document.querySelector('#guide').onclick=()=>window.guideClicks++;const update=()=>document.querySelector('#register').disabled=!(document.querySelector('[aria-checked="true"]')&&document.querySelector('textarea').value.length>=10);document.querySelectorAll('[role="radio"]').forEach(el=>el.onclick=()=>{el.parentElement.querySelectorAll('button').forEach(x=>x.setAttribute('aria-checked',String(x===el)));update();});document.querySelector('textarea').oninput=update;document.querySelector('#register').onclick=()=>document.querySelector('#notice').textContent='리뷰 등록이 완료되었습니다';});
 await page.addScriptTag({content:fs.readFileSync(path.join(__dirname,'../../internal/browserbridge/extension/naver-content.js'),'utf8')});
 const product='반투명 아크릴판 맞춤 재단 매트 엠보아크릴 프라이버시 칸막이 DIY 3T';
 const state=await page.evaluate(product=>post({action:'inspect',product}),product);assert.equal(state.items.length,0,'banner is not a purchase action');assert.equal(state.forms.length,1,'disabled monthly form discovered');assert.equal(state.forms[0].product_matched,true);assert.equal(state.forms[0].submit_disabled,true);
 const fields={form_id:state.forms[0].id,product,text:'좋은 상품 보내주셔서 감사합니다.',rating:5};
 const filled=await page.evaluate(fields=>post({...fields,action:'fill'}),fields);assert.equal(filled.status,'filled',filled.error);assert.equal(await page.locator('#register').isEnabled(),true);
 const result=await page.evaluate(fields=>post({...fields,action:'submit_current'}),fields);assert.equal(result.status,'submitted',result.error);assert.equal(await page.evaluate(()=>guideClicks),0);
 }
 console.log('PASS: supplied monthly form layout, reward banner with/without telemetry, disabled submit, filling and submission; guide never clicked');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
