@uri = http://192.168.100.60:5000

### Health
GET {{uri}}/health

### Chat Completions
POST {{uri}}/v1/chat/completions
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "당신은 친절한 AI 조수입니다."
    },
    {
      "role": "user",
      "content": "양자 역학에 대해 한 문장으로 설명해줘."
    }
  ],
  "stream": false,
  "temperature": 0.7
}

### Completions
POST {{uri}}/v1/completions
Content-Type: application/json

{
  "prompt": "옛날 옛적에 깊은 산속에",
  "n_predict": 128,
  "stream": false
}
