services:
  zifk-gradio:
    container_name: zifk-gradio-spark
    image: edp1096/zifk-gradio-spark:v1
    ports:
      - "7861:7861"
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - "/home/edp1096/.cache/huggingface:/root/.cache/huggingface"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: ""
    command: >
      /bin/bash -c "
      cd ~/zifk-ui &&
      wget -q https://raw.githubusercontent.com/edp1096/dgx_spark_init/main/compose_yaml/zifk/builder/update.sh -O update.sh &&
      chmod +x update.sh &&
      ./update.sh --no-restart &&

      cd app/ui && python download_models.py &&
      cd ~/zifk-ui && python app/app.py --server-name 0.0.0.0 --port 7861
      "
