services:
  heretic:
    image: nvcr.io/nvidia/pytorch:26.02-py3
    container_name: heretic_abliterator
    ipc: host
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - PIP_USE_FEATURE=build-constraint
    volumes:
      - "/home/edp1096/.cache/huggingface:/root/.cache/huggingface"
      - "/home/edp1096/workspace/heretic_models:/root/output"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    # tty: true
    working_dir: /root
    command: >
      /bin/bash -c "
        pip install git+https://github.com/farolone/heretic.git@feat/qwen3.5-moe-support &&
        pip install git+https://github.com/huggingface/transformers.git &&
        heretic --model Qwen/Qwen3.5-35B-A3B-FP8 --save-path /root/output/Qwen3.5-35B-A3B-FP8-heretic
      "