services:
  ltx2-gradio:
    container_name: ltx23-gradio-spark
    image: edp1096/ltx23-gradio-spark:v1
    ports:
      - "7860:7860"
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - PYTHONUNBUFFERED=1
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - "/home/edp1096/.cache/huggingface:/root/.cache/huggingface"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # stdin_open: true
    # tty: true
    entrypoint: ""
    command: >
      /bin/bash -c "
      cd ~/ltx2-ui/LTX-2 &&
      python download_models.py &&
      python app.py --server-name 0.0.0.0
      "