services:
  vllm-head:
    # image: "nvcr.io/nvidia/vllm:26.01-py3"
    image: "vllm/vllm-openai:cu130-nightly-aarch64"
    container_name: vllm-head
    shm_size: 10.24g
    network_mode: "host"
    ipc: "host"
    volumes:
      - "/home/edp1096/.cache/huggingface:/root/.cache/huggingface"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - VLLM_HOST_IP=169.254.141.58
      - RAY_GCS_STORAGE=memory
      - UCX_NET_DEVICES=enp1s0f0np0
      - NCCL_SOCKET_IFNAME=enp1s0f0np0
      - GLOO_SOCKET_IFNAME=enp1s0f0np0
      - TP_SOCKET_IFNAME=enp1s0f0np0
      - OMPI_MCA_btl_tcp_if_include=enp1s0f0np0
      - NCCL_IB_HCA=rocep1s0f0,roceP2p1s0f0
      - NCCL_IB_GID_INDEX=3
      - MASTER_ADDR=169.254.141.58
      - RAY_memory_monitor_refresh_ms=0
      - RAY_memory_usage_threshold=0.99
      - TORCH_NCCL_ASYNC_ERROR_HANDLING=1
      - VLLM_USE_FLASHINFER_MOE_FP4=0
      - VLLM_TEST_FORCE_FP8_MARLIN=1
      - VLLM_NVFP4_GEMM_BACKEND=marlin
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      # - HF_TOKEN=YOUR_HF_TOKEN_HERE
    entrypoint: ""
    command: >
      bash -c "ray start
      --head
      --node-ip-address=169.254.141.58 --port=6379
      --disable-usage-stats
      --include-dashboard=True --dashboard-host=0.0.0.0 --dashboard-port=8265 &&
      vllm serve txn545/Qwen3.5-35B-A3B-NVFP4
      --host 0.0.0.0
      --port 8000
      --tensor-parallel-size 2
      --max-model-len 262144
      --gpu-memory-utilization 0.8
      --max-num-seqs 256
      --max-num-batched-tokens 8192
      --attention-backend flashinfer
      --kv-cache-dtype fp8
      --served-model-name my-model
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --enable-prefix-caching
      --reasoning-parser qwen3
      --disable-log-requests
      --trust-remote-code
      "
    # txn545/Qwen3.5-122B-A10B-NVFP4
    # nvidia/Llama-3.3-70B-Instruct-NVFP4
    # openai/gpt-oss-120b
    # nvidia/Qwen3-8B-NVFP4