"""Minimal toobusy H3 node package without unrelated optional dependencies."""

from .minimax_h3_image_latent import (
    NODE_CLASS_MAPPINGS as IMAGE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .minimax_h3_optional_reference import (
    NODE_CLASS_MAPPINGS as OPTIONAL_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as OPTIONAL_NODE_DISPLAY_NAME_MAPPINGS,
)
from .minimax_h3_semantic_reference import (
    NODE_CLASS_MAPPINGS as SEMANTIC_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SEMANTIC_NODE_DISPLAY_NAME_MAPPINGS,
)


NODE_CLASS_MAPPINGS = {
    **IMAGE_NODE_CLASS_MAPPINGS,
    **OPTIONAL_NODE_CLASS_MAPPINGS,
    **SEMANTIC_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **IMAGE_NODE_DISPLAY_NAME_MAPPINGS,
    **OPTIONAL_NODE_DISPLAY_NAME_MAPPINGS,
    **SEMANTIC_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
