package server

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"image"
	"image/color"
	"image/png"
	"mediaapp/internal/config"
	"mediaapp/internal/jobs"
	"mime/multipart"
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestCharacterSheetCandidateUsesExplicitReviewWorkflow(t *testing.T) {
	var generated bytes.Buffer
	img := image.NewRGBA(image.Rect(0, 0, 8, 8))
	img.Set(2, 2, color.RGBA{R: 220, G: 90, B: 70, A: 255})
	_ = png.Encode(&generated, img)
	engine := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		var request map[string]any
		_ = json.NewDecoder(r.Body).Decode(&request)
		if request["character_sheet_image"] == nil || request["checkpoint"] != "official-int8" || request["size"] != "1536x1024" || request["operation_id"] != "character-sheet-test" {
			t.Fatalf("unexpected character sheet request: %#v", request)
		}
		_ = json.NewEncoder(w).Encode(map[string]any{"data": []map[string]string{{"b64_json": base64.StdEncoding.EncodeToString(generated.Bytes())}}})
	}))
	defer engine.Close()

	dataDir := t.TempDir()
	store, _ := jobs.New(dataDir)
	cfg := config.Config{DataDir: dataDir, Image: config.Image{Backends: map[string]config.ImageBackend{"create": {Endpoint: engine.URL, Model: "krea2-turbo-nvfp4"}}}}
	var body bytes.Buffer
	form := multipart.NewWriter(&body)
	part, _ := form.CreateFormFile("image", "source.png")
	_, _ = part.Write(generated.Bytes())
	_ = form.WriteField("operation_id", "character-sheet-test")
	_ = form.Close()
	req := httptest.NewRequest(http.MethodPost, "/api/images/character-sheet", &body)
	req.Header.Set("Content-Type", form.FormDataContentType())
	res := httptest.NewRecorder()
	New(cfg, store, nil).Handler().ServeHTTP(res, req)
	if res.Code != http.StatusOK || res.Header().Get("Content-Type") != "image/png" {
		t.Fatalf("status=%d content-type=%q body=%s", res.Code, res.Header().Get("Content-Type"), res.Body.String())
	}
	if _, _, err := image.Decode(bytes.NewReader(res.Body.Bytes())); err != nil {
		t.Fatalf("invalid candidate image: %v", err)
	}
}

func TestCharacterSheetStatusProxiesOnlyCorrelatedRuntime(t *testing.T) {
	engine := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if got := r.URL.Query().Get("operation_id"); got != "character-sheet-test" {
			t.Fatalf("operation_id=%q", got)
		}
		_ = json.NewEncoder(w).Encode(map[string]any{
			"operation": map[string]any{"operation_id": "character-sheet-test", "phase": "sampling", "progress": 0.7},
		})
	}))
	defer engine.Close()
	dataDir := t.TempDir()
	store, _ := jobs.New(dataDir)
	cfg := config.Config{DataDir: dataDir, Image: config.Image{Backends: map[string]config.ImageBackend{"create": {Endpoint: engine.URL}}}}
	req := httptest.NewRequest(http.MethodGet, "/api/images/character-sheet/status?operation_id=character-sheet-test", nil)
	res := httptest.NewRecorder()
	New(cfg, store, nil).Handler().ServeHTTP(res, req)
	if res.Code != http.StatusOK || !bytes.Contains(res.Body.Bytes(), []byte(`"phase":"sampling"`)) {
		t.Fatalf("status=%d body=%s", res.Code, res.Body.String())
	}
}
