package server

import (
	"fmt"
	"image"
	"image/color"
	"image/png"
	"mediaapp/internal/jobs"
	"os"
	"path/filepath"
	"strings"
)

// materializeSequenceIdentity links the previous scene result into this job's
// persisted inputs. Full-frame edits use Identity Edit; region edits use
// AnyPaint so the mask participates in generation instead of post-compositing.
func (s *Server) materializeSequenceIdentity(job jobs.Job) error {
	params := decodeImageJobParams(job.Params)
	previousID := params.SequencePreviousJobID
	if previousID == "" {
		return nil
	}
	previous, ok := s.jobs.Get(previousID)
	if !ok || previous.Kind != "image" {
		return fmt.Errorf("previous sequence image no longer exists")
	}
	if previous.Status != "completed" || previous.OutputURL == "" {
		return fmt.Errorf("previous sequence image did not complete")
	}
	source := s.jobs.OutputPath(filepath.Base(previous.OutputURL))
	ext := strings.ToLower(filepath.Ext(source))
	if ext == "" {
		ext = ".png"
	}
	region := params.SequenceRegion
	role := "identity"
	if region != "all" {
		role = "anypaint"
	}
	dir := filepath.Join(s.dataDir, "inputs", job.ID, role)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	destination := filepath.Join(dir, "0"+ext)
	if _, err := os.Stat(destination); err != nil && !os.IsNotExist(err) {
		return err
	} else if os.IsNotExist(err) {
		if err := linkOrCopyFile(source, destination); err != nil {
			return fmt.Errorf("prepare previous sequence image: %w", err)
		}
	}
	if region == "all" {
		return nil
	}
	return s.materializeSequenceAnyPaintMask(job, source)
}

// materializeSequenceAnyPaintMask creates a normalized generation mask after
// the preceding scene exists. White pixels are regenerated by AnyPaint while
// the known image outside the mask is preserved by the diffusion workflow.
func (s *Server) materializeSequenceAnyPaintMask(job jobs.Job, source string) error {
	region := decodeImageJobParams(job.Params).SequenceRegion
	if region == "all" {
		return nil
	}
	if region == "custom" {
		dir := filepath.Join(s.dataDir, "inputs", job.ID, "anypaint-mask")
		entries, err := os.ReadDir(dir)
		if err != nil || len(entries) == 0 {
			return fmt.Errorf("painted sequence mask is missing")
		}
		return nil
	}
	input, err := os.Open(source)
	if err != nil {
		return err
	}
	config, _, err := image.DecodeConfig(input)
	_ = input.Close()
	if err != nil || config.Width <= 0 || config.Height <= 0 {
		return fmt.Errorf("read sequence source dimensions: %w", err)
	}
	mask := image.NewGray(image.Rect(0, 0, config.Width, config.Height))
	paint := func(x0, y0, x1, y1 float64) {
		rect := image.Rect(int(x0*float64(config.Width)), int(y0*float64(config.Height)), int(x1*float64(config.Width)), int(y1*float64(config.Height))).Intersect(mask.Bounds())
		for y := rect.Min.Y; y < rect.Max.Y; y++ {
			for x := rect.Min.X; x < rect.Max.X; x++ {
				mask.SetGray(x, y, color.Gray{Y: 255})
			}
		}
	}
	switch region {
	case "left":
		paint(0, 0, .58, 1)
	case "right":
		paint(.42, 0, 1, 1)
	case "upper":
		paint(0, 0, 1, .58)
	case "lower":
		paint(0, .42, 1, 1)
	case "left-arm":
		paint(0, .08, .38, 1)
		paint(.38, .38, .48, 1)
	case "right-arm":
		paint(.62, .08, 1, 1)
		paint(.52, .38, .62, 1)
	default:
		return fmt.Errorf("unsupported sequence region %q", region)
	}
	dir := filepath.Join(s.dataDir, "inputs", job.ID, "anypaint-mask")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	destination := filepath.Join(dir, "0.png")
	if _, err := os.Stat(destination); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	output, err := os.OpenFile(destination, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
	if err != nil {
		return err
	}
	encodeErr := png.Encode(output, mask)
	closeErr := output.Close()
	if encodeErr != nil {
		return encodeErr
	}
	return closeErr
}
