"""Generate the document tool schema shared by Talk and the document service."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
def S(n=4000,**kw):return dict(type='string',maxLength=n,**kw)
def N(lo=0,hi=100):return dict(type='number',minimum=lo,maximum=hi)
def A(item,n=500):return dict(type='array',items=item,maxItems=n)
def O(props,required=()):return dict(type='object',properties=props,required=list(required),additionalProperties=False)
def E(*v):return dict(type='string',enum=list(v))
def R(name):return {'$ref':'#/$defs/'+name}
B={'type':'boolean'}
style=O({'font':S(80),'size':N(6,72),'bold':B,'italic':B,'underline':B,'strike':B,'color':S(6),'background':S(6),'border':S(6),'align':E('left','center','right','justify'),'valign':E('top','center','bottom'),'indent':N(0,144),'spacing':N(0,144),'margin':N(0,144),'line_spacing':N(1,3),'num_fmt':S(100)})
run=O({'text':S(),'style':R('style'),'link':S(2048)},['text'])
text={'anyOf':[S(),A(R('run'),200)]}
image=O({'image_id':S(200),'width_cm':N(1,16),'caption':S(240)},['image_id'])
image['description']='Use an existing conversation image attachment ID. Default width is 12 cm.'
cell={'anyOf':[S(500),O({'text':R('text'),'style':R('style'),'width':N(.001,1000),'col_span':N(1,8),'row_span':N(1,100),'blocks':A(R('block'),100)})]}
cell['description']='width is a relative grid width, in the same units as table.widths. Cells in the same column must agree. A merged cell width is the sum of spanned columns. Missing widths default toward equal columns; conflicts are rejected.'
chart=O({'kind':E('bar','line','pie','doughnut','area','scatter'),'title':S(120),'labels':A(S(80),100),'series':A(O({'name':S(80),'values':A(N(-1e12,1e12),100),'color':S(6)},['name','values']),8),'legend':B},['kind','labels','series'])
block=O({'type':E('paragraph','heading','quote','list','table','image','chart','columns','page_break','toc','bookmark','footnote','endnote','comment','equation','checkbox','shape','media'),'text':R('text'),'style':R('style'),'level':N(1,6),'items':A(R('text'),100),'ordered':B,'rows':A(A(R('cell'),8),100),'widths':A(N(.001,1000),8),'image':R('image'),'chart':R('chart'),'columns':A(A(R('block')),3),'name':S(40),'note':S(),'numerator':S(200),'denominator':S(200),'checked':B,'shape':E('rect','ellipse','line','arrow','textbox'),'fill':S(6),'line':S(6),'link':S(2048),'wrap':E('inline','square','topBottom'),'fit':E('contain','cover'),'media':O({'media_id':S(200)},['media_id']),**{k:N(0,100) for k in ['x','y','w','h']}},['type'])
block['description']='Ordered content. paragraph/heading: text string or runs; list: items; table: rows, first row header, merged cells omit covered cells; image: image attachment; chart: chart; columns: 2–3 arrays of blocks. x/y/w/h are inches for slide objects. DOCX/PDF: toc, comment, checkbox. DOCX/HWP/HWPX: footnote, equation, bookmark. HWP/HWPX: endnote. PPTX: chart, shape, media (existing MP3/WAV/MP4 attachment, max 3, 8 MiB total). PPTX excludes footnotes/toc/comments/equations. No code or filesystem paths.'
page=O({'size':E('A4','A3','LETTER'),'orientation':E('portrait','landscape'),'margin':N(10,100),'columns':N(1,3),'header':S(240),'footer':S(240),'first_header':S(240),'even_header':S(240),'first_footer':S(240),'even_footer':S(240),'page_numbers':B,'break_before':B})
page['description']='Margin in points. HWP/HWPX page properties are document-level; section page supports break_before only. First-page header/footer variants are DOCX/PDF only.'
section=O({'heading':S(240),'paragraphs':{'type':'array','items':S()},'table':A(A(S(500),8),100),'images':A(R('image'),6),'blocks':A(R('block')),'page':R('page')})
section['description']='Use ordered blocks OR legacy heading/paragraphs/table/images. Legacy paragraphs are a JSON string array with no paragraph-count limit; total document text is capped.'
slide=O({'title':S(120),'bullets':A(S(200),8),'table':{'anyOf':[A(A(S(500),8),100),O({'rows':A(A(R('cell'),8),100),'widths':A(N(.001,1000),8),'style':R('style')},['rows'])]},'images':A(R('image'),6),'blocks':A(R('block')),'notes':S(8000),'layout':E('single','two-column')},['title'])
slide['description']='Use blocks OR legacy bullets/table/images. For native tables use table:{rows,widths,style} or blocks:[{type:table,rows,widths,style}]. widths are relative COLUMN widths, e.g. [8,12,20,25,35]; cells share column widths and merged cells sum them. Tables may split with repeated headers. Use returned presentation metadata for actual slides/splits; never infer visual appearance without inspecting the file.'
value={'anyOf':[S(2000),{'type':'number'},B,{'type':'null'},O({'formula':S(512)},['formula']),O({'date':S(10)},['date']),O({'runs':A(R('run'),200)},['runs'])]}
sheet=O({'name':S(31),'columns':A(O({'title':S(120),'width':N(6,60),'format':E('general','number','integer','currency','percent','date')},['title']),32),'rows':A(A(value,32),1000),'freeze_header':B,'filter':B,'orientation':E('portrait','landscape'),'cells':A(O({'cell':S(12),'style':R('style'),'link':S(2048),'note':S(2000),'validation':O({'type':E('list','whole','decimal','textLength'),'values':A(S(100),100),'min':N(-1e12,1e12),'max':N(-1e12,1e12),'allow_blank':B},['type'])},['cell']),2000),'merges':A(S(30),100),'conditional_formats':A(O({'range':S(30),'operator':E('greaterThan','lessThan','equal','greaterThanOrEqual','lessThanOrEqual'),'value':N(-1e12,1e12),'style':R('style')},['range','operator','value','style']),100),'images':A(O({'image':R('image'),'cell':S(12),'width':N(10,1200),'height':N(10,1200)},['image','cell']),6),'charts':A(O({'kind':E('bar','line','pie','doughnut','area','scatter'),'title':S(120),'cell':S(12),'categories':S(30),'series':A(O({'name':S(80),'values':S(30)},['name','values']),8)},['kind','cell','categories','series']),8),'pivots':A(O({'name':S(40),'source':S(30),'destination':S(30),'rows':A(S(120),8),'columns':A(S(120),8),'values':A(O({'field':S(120),'function':E('Sum','Count','Average','Min','Max')},['field','function']),8)},['name','source','destination','rows','values']),4),'shapes':A(O({'cell':S(12),'text':S(1000),'kind':E('rect','ellipse','line','arrow')},['cell','text','kind']),20),'row_options':A(O({'index':N(1,1001),'hidden':B,'level':N(0,7),'size':N(1,409)},['index']),1001),'column_options':A(O({'index':N(1,32),'hidden':B,'level':N(0,7),'size':N(1,409)},['index']),32),'freeze':O({'rows':N(0,1000),'columns':N(0,32)}),'hidden':B,'protection':O({'password':S(64)}),'table_name':S(40),'print':O({'area':S(30),'repeat_rows':S(20),'repeat_columns':S(20),'header':S(200),'footer':S(200),'margin':N(0,2),'scale':N(10,400),'paper':E('A4','A3','LETTER')})},['name','columns','rows'])
sheet['description']='Row 1 is the header. Max 20000 workbook cells. Formula functions: SUM, AVERAGE, COUNT, COUNTA, MIN, MAX, IF, AND, OR, NOT, ROUND, ROUNDUP, ROUNDDOWN, ABS, COUNTIF, SUMIF, IFERROR, VLOOKUP, XLOOKUP, SUMIFS, COUNTIFS. Supplied cells only; no external/dynamic references. Merge covered cells must be empty. Chart/pivot ranges use same-sheet A1 notation; pivot destinations must be outside supplied data. Print margins in inches; image size in pixels.'
schema=O({'format':E('docx','pptx','xlsx','hwp','hwpx','pdf'),'title':S(240),'filename':S(80),'page':R('page'),'theme':O({'preset':E('business','minimal','dark'),'font':S(80),'accent':S(6),'background':S(6),'ratio':E('wide','standard')}),'sections':A(R('section'),80),'slides':A(R('slide'),40),'sheets':A(R('sheet'),8)},['format','title'])
schema['$defs']=dict(style=style,run=run,text=text,image=image,cell=cell,chart=chart,block=block,page=page,section=section,slide=slide,sheet=sheet)
(root/'document-schema.json').write_text(json.dumps(schema,ensure_ascii=False,indent=2)+'\n')
