services:
  vllm:
    # image: "nvcr.io/nvidia/vllm:26.01-py3"
    # image: "vllm/vllm-openai:cu130-nightly-aarch64"
    image: "edp1096/vllm-node:v1"
    container_name: vllm-single
    network_mode: "host"
    ipc: "host"
    volumes:
      - "/home/edp1096/.cache/huggingface:/root/.cache/huggingface"
      # - "/home/edp1096/workspace/heretic_models:/root/models"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - VLLM_MARLIN_USE_ATOMIC_ADD=1
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
      # - TORCH_NCCL_ASYNC_ERROR_HANDLING=1
      # - VLLM_USE_FLASHINFER_MOE_FP4=0
      # - VLLM_TEST_FORCE_FP8_MARLIN=1
      # - VLLM_NVFP4_GEMM_BACKEND=marlin
      # - HF_TOKEN=YOUR_HF_TOKEN_HERE
    entrypoint: vllm serve
    command: >
      edp1096/Huihui-Qwen3.5-35B-A3B-abliterated-FP8
      --host 0.0.0.0
      --port 8000
      --max-model-len 262144
      --gpu-memory-utilization 0.8
      --max-num-seqs 256
      --max-num-batched-tokens 16384
      --kv-cache-dtype fp8
      --attention-backend flashinfer
      --served-model-name my-model
      --enable-prefix-caching
      --enable-auto-tool-choice
      --tool-call-parser qwen3_coder
      --reasoning-parser qwen3
      --trust-remote-code

    # --default-chat-template-kwargs '{"enable_thinking": false}'
    # edp1096/Huihui-Qwen3.5-35B-A3B-abliterated-FP8
    # /root/models/Huihui-Qwen3.5-35B-A3B-abliterated-FP8
    # Qwen/Qwen3.5-9B
    # Kbenkhaled/Qwen3.5-35B-A3B-quantized.w4a16
    # Ankushbl6/Qwen3.5-35B-A3B-AWQ-4bit
    # txn545/Qwen3.5-35B-A3B-NVFP4
    # txn545/Qwen3.5-27B-NVFP4
    # Qwen/Qwen3.5-35B-A3B
    # Qwen/Qwen3.5-35B-A3B-FP8
    # txn545/Qwen3.5-122B-A10B-NVFP4
    # nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8
    # nvidia/Qwen3-8B-NVFP4
    # Qwen/Qwen2.5-Math-1.5B-Instruct
    # openai/gpt-oss-120b
    # nvidia/Llama-3.3-70B-Instruct-NVFP4