@uri = http://192.168.100.60:8000
# @model = Qwen/Qwen2.5-Math-1.5B-Instruct
# @model = openai/gpt-oss-120b
# @model = nvidia/Llama-3.3-70B-Instruct-NVFP4
# @model = nvidia/Llama-3.3-70B-Instruct-NVFP4
# @model = nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-FP8
@model = nvidia/Qwen3-8B-NVFP4

### Korean greeting test
POST {{uri}}/v1/chat/completions
Content-Type: application/json

{
  "model": "{{model}}",
  "messages": [
    {
        "role": "user",
        "content": "안녕? 너는 누구야? DGX Spark에서 잘 돌아가고 있어?"
    }
  ]
}

### GPU haiku in English
POST {{uri}}/v1/chat/completions
Content-Type: application/json

{
  "model": "{{model}}",
  "messages": [
    {
        "role": "user",
        "content": "Write a haiku about a GPU"
    }
  ]
}

### GPU haiku in Korean
POST {{uri}}/v1/chat/completions
Content-Type: application/json

{
  "model": "{{model}}",
  "messages": [
    {
        "role": "user",
        "content": "Write a haiku about a GPU. 한국말로 답해라."
    }
  ]
}

### Health check
GET {{uri}}/health