package server

import (
	"io/fs"
	"net/http"
)

func (s *Server) routes(web fs.FS) *http.ServeMux {
	mux := http.NewServeMux()
	mux.HandleFunc("/api/plugins", s.pluginAPI)
	mux.HandleFunc("/api/plugins/", s.pluginAPI)
	s.browser.Register(mux)
	mux.HandleFunc("/api/health", s.health)
	mux.HandleFunc("/api/emergency/clear-queue", s.emergencyQueue)
	mux.HandleFunc("/api/config", s.configuration)
	mux.HandleFunc("/api/credentials/huggingface", s.huggingFaceToken)
	mux.HandleFunc("/api/models/prepare", s.modelPreparation)
	mux.HandleFunc("/api/ssh/key-store", s.sshKeyStore)
	mux.HandleFunc("/api/support", s.supportServices)
	mux.HandleFunc("/api/media/yt-dlp", s.mediaRuntime)
	mux.HandleFunc("/api/media/yt-dlp/", s.mediaRuntime)
	mux.HandleFunc("/api/runtime", s.runtimeStatus)
	mux.HandleFunc("/api/runtime/catalog/parse", s.runtimeCatalogParse)
	mux.HandleFunc("/api/runtime/probe", s.runtimeProbe)
	mux.HandleFunc("/api/runtime/network/discover", s.networkDiscover)
	mux.HandleFunc("/api/runtime/", s.runtimeAction)
	mux.HandleFunc("/api/models", s.models)
	mux.HandleFunc("/api/images", s.uploadImage)
	mux.HandleFunc("/api/images/", s.image)
	mux.HandleFunc("/api/files", s.uploadFile)
	mux.HandleFunc("/api/files/", s.file)
	mux.HandleFunc("/api/media", s.mediaUsage)
	mux.HandleFunc("/api/media/source", s.uploadSource)
	mux.HandleFunc("/api/media/transcript/", s.attachmentTranscript)
	mux.HandleFunc("/api/memories", s.memories)
	mux.HandleFunc("/api/memories/", s.memory)
	mux.HandleFunc("/api/knowledge/collections", s.knowledgeCollections)
	mux.HandleFunc("/api/knowledge/collections/", s.knowledgeCollection)
	mux.HandleFunc("/api/knowledge/documents", s.knowledgeDocuments)
	mux.HandleFunc("/api/knowledge/documents/", s.knowledgeDocument)
	mux.HandleFunc("/api/knowledge/sources", s.collectKnowledgeSource)
	mux.HandleFunc("/api/knowledge/jobs", s.knowledgeJobList)
	mux.HandleFunc("/api/knowledge/jobs/", s.knowledgeJobAction)
	mux.HandleFunc("/api/knowledge/search", s.searchKnowledge)
	mux.HandleFunc("/api/search/page", s.searchConversationPage)
	mux.HandleFunc("/api/search", s.searchConversations)
	mux.HandleFunc("/api/workflows", s.workflowCatalog)
	mux.HandleFunc("/api/workflows/", s.workflowItem)
	mux.HandleFunc("/api/skills", s.skillCatalog)
	mux.HandleFunc("/api/skills/", s.skillItem)
	mux.HandleFunc("/api/tool-audit", s.toolAudits)
	mux.HandleFunc("/api/asr/transcribe", s.transcribeVoice)
	mux.HandleFunc("/api/tts/speech", s.synthesizeSpeech)
	mux.HandleFunc("/api/tts/preview", s.previewSpeech)
	mux.HandleFunc("/api/ssh/hosts", s.sshHosts)
	mux.HandleFunc("/api/ssh/hosts/", s.sshHost)
	mux.HandleFunc("/api/ssh/keys", s.sshKeys)
	mux.HandleFunc("/api/ssh/keys/", s.sshKey)
	mux.HandleFunc("/api/tool-approvals/", s.toolApproval)
	mux.HandleFunc("/api/messages/", s.messageAction)
	mux.HandleFunc("/api/groups", s.groups)
	mux.HandleFunc("/api/groups/", s.group)
	mux.HandleFunc("/api/sessions", s.sessions)
	mux.HandleFunc("/api/sessions/bulk-delete", s.bulkDeleteSessions)
	mux.HandleFunc("/api/sessions/", s.session)
	mux.HandleFunc("/api/chat", s.chat)
	mux.HandleFunc("/api/chat/steer", s.steerChat)
	mux.Handle("/", spaHandler(web))

	return mux
}
