import { expect, test } from '@playwright/test';
import { expectControlValue, selectOption, optionTexts } from './select-helpers.js';

test('header, runtime and preparation share names without changing API IDs', async ({ page, request }) => {
 const cfg = await (await request.get('/api/config')).json();
 const catalog = cfg.runtime.catalog;
 const native = catalog.bundles.find(b => b.id === 'qwen38fn_exl3');
 cfg.runtime.mode = 'managed';
 cfg.model.default_model = native.model_id;
 cfg.model.model_type = native.model_type;
 const components = catalog.components.filter(c => native.components.includes(c.id)).map(c => ({...c,...native.bindings[c.id],health:'online',status:'running'}));
 const runtime = {selected_bundle:native.id,bundles:catalog.bundles,components,operation:{},docker:'online'};
 await page.route('**/api/config', route => route.fulfill({json:cfg}));
 await page.route('**/api/models', route => route.fulfill({json:[native.model_id]}));
 await page.route('**/api/runtime', route => route.fulfill({json:runtime}));
 await page.goto('/');
 await expect(page.locator('.model-name')).toHaveText(native.name);
 await expect(page.locator('.model-menu-toggle')).not.toContainText('huihui');
 await page.getByRole('button', {name:'모델 및 대화 설정',exact:true}).click();
 const modelSelect = page.getByRole('combobox', {name:'모델 선택',exact:true});
 await expectControlValue(modelSelect,native.model_id);
 expect(await optionTexts(modelSelect)).toEqual([native.name]);
 await page.getByRole('button', {name:'대화 제어 닫기'}).click();
 await page.locator('.status').click();
 await expect(page.locator('.runtime-heading strong')).toHaveText(native.name);
 await expect(page.getByRole('group', {name:'Nemotron 3.5 ASR'})).toContainText('Q5_K');
 await expect(page.getByRole('group', {name:'Nemotron 3.5 ASR'})).toContainText('화자 구분 Q8_0');
 await page.locator('.settings-button').click();
 await expect(page.locator('.settings-bundle-card')).toContainText('Abliterated · EXL3 3bit');
 await expect(page.locator('.settings-bundle-card')).not.toContainText('qwen38fn_exl3');
 await page.getByRole('tab', {name:'시스템'}).click();
 await page.getByRole('button', {name:'모델 준비',exact:true}).click();
 const downloadModel = page.getByRole('combobox', {name:'모델',exact:true});
 await selectOption(downloadModel,native.id);
 await expect(downloadModel).toContainText(native.name);
 const weights = page.getByRole('combobox', {name:'가중치',exact:true});
 await expectControlValue(weights,'abliterated');
 await expect(weights).toBeDisabled();
 expect(await optionTexts(weights)).toEqual(['Abliterated']);
 await expect(page.getByText('가중치 형식 · EXL3 3bit HQ h6 ng6')).toBeVisible();
 await expect(page.getByRole('link', {name:/alesha-pro\/Huihui/})).toBeVisible();
 await selectOption(downloadModel,'flash-next');
 await selectOption(weights,'huihui_lil');
 await expect(weights).toContainText('Abliterated · QAD');
 await expect(page.getByRole('link', {name:/edp1096\/Huihui-Qwen3.8/})).toBeVisible();
 await selectOption(downloadModel,'flash-next-tp2');
 await expect(weights).toBeDisabled();
 await expectControlValue(weights,'abliterated');
 await expect(downloadModel).not.toContainText('Huihui');
});
