import {expect,test} from '@playwright/test';

test('library supports persistent skills, builtin copy, selection and deletion',async({page,request})=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto('/');
 await page.getByRole('button',{name:'▤ 라이브러리',exact:true}).click();
 await page.locator('.settings-button').click();
 await page.getByRole('tab',{name:'기능',exact:true}).click();
 await page.getByRole('button',{name:'스킬·기록',exact:true}).click();
 await page.getByRole('button',{name:'스킬 관리',exact:true}).click();
 await page.getByRole('button',{name:'새 스킬',exact:true}).click();
 await page.getByLabel('스킬 이름',{exact:true}).fill('review-e2e');
 await page.getByLabel('사용할 상황',{exact:true}).fill('코드 변경을 검토할 때 사용합니다.');
 await page.getByLabel('작업 절차',{exact:true}).fill('1. 변경된 코드를 확인한다.\n2. 검증 근거를 정리한다.');
 await page.getByRole('button',{name:'저장',exact:true}).click();
 await expect(page.getByRole('button',{name:'review-e2e',exact:true})).toBeVisible();
 await page.reload();
 await page.getByRole('button',{name:'▤ 라이브러리',exact:true}).click();
 await page.getByRole('button',{name:'스킬',exact:true}).click();
 await page.getByRole('button',{name:'review-e2e',exact:true}).click();
 await expect(page.getByLabel('작업 절차',{exact:true})).toHaveValue(/검증 근거/);
 await page.getByRole('button',{name:'목록으로',exact:true}).click();
 await page.getByRole('button',{name:'web-research',exact:true}).click();
 await expect(page.getByLabel('작업 절차',{exact:true})).toHaveAttribute('readonly','');
 await page.getByRole('button',{name:'복사해서 수정',exact:true}).click();
 await page.getByLabel('스킬 이름',{exact:true}).fill('web-copy-e2e');
 await page.getByRole('button',{name:'저장',exact:true}).click();
 await expect(page.getByRole('button',{name:'web-copy-e2e',exact:true})).toBeVisible();
 await page.screenshot({path:'/tmp/sparktalk-skill-library.png'});
 await page.setViewportSize({width:390,height:760});
 await page.getByRole('button',{name:'review-e2e',exact:true}).click();
 await expect(page.getByLabel('작업 절차',{exact:true})).toBeVisible();
 await page.screenshot({path:'/tmp/sparktalk-skill-editor-mobile.png'});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
 await page.getByRole('button',{name:'목록으로',exact:true}).click();
 await page.setViewportSize({width:1280,height:720});
 await page.getByRole('button',{name:'대화로 돌아가기',exact:true}).click();
 // Create a real conversation to verify selection without calling an LLM.
 const session=await (await request.post('/api/sessions',{data:{title:'Skill UI test'}})).json();
 await page.reload();
 await page.getByRole('button',{name:'입력 도구 열기',exact:true}).click();await page.getByRole('button',{name:'스킬·작업 절차',exact:true}).click();
 await page.getByRole('button',{name:/^review-e2e/}).click();
 await expect(page.locator('.composer textarea')).toHaveValue('@skill:review-e2e\n');
 await page.getByRole('button',{name:'review-e2e 지정 해제',exact:true}).click();
 await expect(page.locator('.composer textarea')).toHaveValue('');
 await page.getByRole('button',{name:'▤ 라이브러리',exact:true}).click();
 await page.getByRole('button',{name:'스킬',exact:true}).click();
 await page.getByRole('button',{name:'review-e2e',exact:true}).click();
 await page.getByRole('button',{name:'삭제',exact:true}).click();
 await page.getByRole('button',{name:'삭제 확인',exact:true}).click();
 await expect(page.getByRole('button',{name:'review-e2e',exact:true})).toHaveCount(0);
 await request.delete('/api/skills/web-copy-e2e');
 await request.delete(`/api/sessions/${session.id}`);
 expect(errors).toEqual([]);
});
