services:
  ltx2-ui:
    container_name: ltx2-ui
    image: nvcr.io/nvidia/pytorch:26.02-py3
    ports:
      - "7860:7860"
    environment:
      - PIP_ROOT_USER_ACTION=ignore
    volumes:
      - "/home/edp1096/.cache/huggingface:/root/.cache/huggingface"
      - "/home/edp1096/workspace/ltx2-ui:/root/ltx2-ui"
      # - "/home/edp1096/workspace/.claude:/root/.claude"
      # - "/home/edp1096/workspace/.claude.json:/root/.claude.json"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    stdin_open: true
    tty: true
    command: "/bin/bash"
    # command: >
    #   bash -c "
    #     bash /root/ltx2-ui/setup.sh &&
    #     cd /root/ltx2-ui/LTX-2 &&
    #     python app.py
    #   "
